#!/bin/bash

declare -a PROJECTS

PROJECTS[0]=$HOME/dev/GitHub/espresso-utils
PROJECTS[1]=$HOME/dev/GitHub/Emoji
PROJECTS[2]=$HOME/dev/GitHub/TextBuilder
PROJECTS[3]=$HOME/dev/GitHub/lint-rules
PROJECTS[4]=$HOME/dev/GitHub/SparseBuilders
PROJECTS[5]=$HOME/dev/GitHub/RxPermission
PROJECTS[6]=$HOME/dev/GitHub/OnActivityResult
PROJECTS[7]=$HOME/dev/GitHub/junit-rules
PROJECTS[8]=$HOME/dev/GitHub/gradle-android-apk-size-plugin
# PROJECTS[9]=$HOME/dev/GitHub/gradle-dependency-graph-generator-plugin

# PROJECTS[9]=$HOME/dev/GitHub/gradle-android-javadoc-plugin/build.gradle
# PROJECTS[10]=$HOME/dev/GitHub/gradle-android-junit-jacoco-plugin/build.gradle
# PROJECTS[11]=$HOME/dev/GitHub/gradle-code-quality-tools-plugin/build.gradle

for i in "${PROJECTS[@]}"; do
  cd "$i" || exit

  git checkout master
  git up
  git c -b ktlint0.19.0

  sed -i "s/toolVersion = '0.15.0'/toolVersion = '0.19.0'/g" "$i/build.gradle"

  git commit -a -m "Update ktlint to 0.19.0"
  git push origin ktlint0.19.0
  hub pull-request -m "Update ktlint to 0.19.0" -F -
done

exit 0;